### ISSUE TITLE
Hello, This project is not work

### ISSUE THREAD

**Issue by ylmw0131** [prabirshrestha/socket-io-net#1]
The project is not work.
Why? The CPU keep in 100% when open the 'Echo' Sample.

**Comment by prabirshrestha** [comment]
Thats coz the code is not implemented and it is not usable at the moment. 

https://github.com/prabirshrestha/socket-io-net/blob/owin15/src/socket.io.net/Transports/SocketIoXhrPollingTransport.cs
https://github.com/prabirshrestha/socket-io-net/blob/owin15/src/socket.io.net/Transports/SocketIoWebSocketTransport.cs
